DROP TABLE IF EXISTS PRINCE;
DROP TABLE IF EXISTS WOUNDED_PRINCE;

CREATE TABLE PRINCE
(
    ID               BIGINT NOT NULL AUTO_INCREMENT,
    PRINCE_LEVEL     VARCHAR(25),
    SKILL_TYPE       VARCHAR(25),
    EXPERIENCE_YEARS INTEGER,
    STATUS           VARCHAR(25) DEFAULT 'HEALTHY',
    PRINCE_ID        VARCHAR(50),
    NAME             VARCHAR(50),
    AGE              INTEGER,
    CREATED_AT       DATETIME,
    UPDATED_AT       DATETIME,
    PRIMARY KEY (ID),
    UNIQUE (`PRINCE_ID`)
);

CREATE TABLE WOUNDED_PRINCE
(
    ID         BIGINT NOT NULL AUTO_INCREMENT,
    PRINCE_ID  VARCHAR(50),
    NAME       VARCHAR(50),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    PRIMARY KEY (ID)
);
